server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 1

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huseyin-bacanak/properties

